# OpenSBI and Linux kernel boot
targets:
  main:
    drivers:
      QEMUDriver:
        qemu_bin: qemu-system-riscv64
        machine: virt
        cpu: rv64
        memory: '1G'
        bios: opensbi
        kernel: kernel
        extra_args: '-smp 4 -netdev user,id=net0 -device virtio-net-device,netdev=net0'
      ShellDriver:
        name: 'test'
        login_prompt: " login: "
        prompt: "# "
        username: "root"
        password: "root"
      ShellStrategy: {}
images:
  # QEMU uses fw_dynamic.bin by default
  opensbi: !template $LG_IMAGES/$LG_OPENSBI
  kernel: !template $LG_IMAGES/$LG_LINUX

tools:
  qemu-system-riscv64: !template $LG_QEMU_RISCV64
