targets:
  main:
    resources:
      USBSerialPort:
        match:
          ID_PATH: pci-0000:00:14.0-usb-0:2.2:1.0
      ModbusTCPCoil:
        host: 192.168.1.100
        coil: 4
    drivers:
      SerialDriver: {}
      ModbusTCPPowerDriver:
        delay: 0.5
        downtime: 3.0
      UBootDriver:
        prompt: '=> '
      ShellDriver:
        login_prompt: '.*login: '
        username: 'root'
        password: 'root'
        prompt: '# '
      UBootStrategy: {}
