slot1:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: UNKNOWN
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 5
  TFTPProvider:
    internal: "/srv/atftp/slot1/"
    external: "slot1/"
slot2:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.3:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 1
  TFTPProvider:
    internal: "/srv/atftp/slot2/"
    external: "slot2/"
slot3:
  location: home-lab
  USBFlashableDevice:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.4.1
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.2:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 4
  TFTPProvider:
    internal: "/srv/atftp/slot3/"
    external: "slot3/"
slot4:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.3:1.2
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 0
  TFTPProvider:
    internal: "/srv/atftp/slot4/"
    external: "slot4/"
slot5:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: UNKNOWN
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 3
  TFTPProvider:
    internal: "/srv/atftp/slot5/"
    external: "slot5/"
slot6:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: UNKNOWN
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 2
  TFTPProvider:
    internal: "/srv/atftp/slot6/"
    external: "slot6/"
slot7:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: UNKNOWN
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 7
  TFTPProvider:
    internal: "/srv/atftp/slot7/"
    external: "slot7/"
slot8:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.1:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 6
  TFTPProvider:
    internal: "/srv/atftp/slot8/"
    external: "slot8/"
