targets:
  main:
    resources:
      RemotePlace:
        name: !template ${LG_PLACE}
    drivers:
      SerialDriver: {}
      ModbusTCPPowerDriver:
        delay: 1.0
        downtime: 3.0
      UBootDriver:
        prompt: '=> '
      ShellDriver:
        name: 'test'
        login_prompt: '.*login: '
        username: 'root'
        password: 'root'
        prompt: 'setup# '
      UBootStrategy: {}
