targets:
  main:
    resources:
      RemotePlace:
        name: !template ${LG_PLACE}
      NetworkService:
        address: orangepipcplus.local
        username: root
        password: root
    drivers:
    - TFTPProviderDriver: {}
    - SerialDriver: {}
    - ModbusTCPPowerDriver:
      cls: 'ModbusTCPPowerDriver'
      delay: 0.5
      downtime: 3.0
    - UBootDriver:
      cls: 'UBootDriver'
      prompt: '=> '
      boot_command: !template "ext4load mmc 0:1 $$kernel_addr_r /boot/test/$LG_LINUX; ext4load mmc 0:1 $$fdt_addr_r /boot/test/$LG_DTB; bootz $$kernel_addr_r - $$fdt_addr_r"
      boot_timeout: 120
    - ShellDriver:
      cls: 'ShellDriver'
      name: 'setup'
      login_timeout: 60 
      login_prompt: '.*login: '
      username: 'root'
      password: 'root'
      prompt: 'setup# '
    - ShellDriver:
      cls: 'ShellDriver'
      name: 'test'
      login_timeout: 60 
      login_prompt: '.*login: '
      username: 'root'
      password: 'root'
      prompt: '# '
    - SSHDriver:
      cls: 'SSHDriver'
      explicit_sftp_mode: False
      explicit_scp_mode: True
    - DoubleBootStrategy:
      cls: 'DoubleBootStrategy'
      bindings:
        'setup_shell': 'setup'
        'test_shell': 'test'

paths:
  test: /boot/test

images:
  kernel: !template $LG_IMAGES/$LG_LINUX
  dtb:    !template $LG_IMAGES/$LG_DTB
