targets:
  main:
    resources:
      RemotePlace:
        name: !template ${LG_PLACE}
    drivers:
      SerialDriver: {}
      ModbusTCPPowerDriver:
        delay: 2.0
        downtime: 3.0
      KendryteFlashDriver:
        flasher: 'ktool.py'
        board: 'bit_mic'
        baudrate: 1500000
        image: 'kernel'
        prompt: 'Rebooting...'
      ShellDriver:
        name: 'test'
        login_prompt: '.*login: '
        username: 'root'
        prompt: '~ # '
      KendryteStrategy: {}

images:
  kernel:  !template $LG_IMAGES/$LG_LINUX
