orangepi-pc-plus:
  location: lab-slot1
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.2:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 6
orangepi-zero2w:
  location: lab-slot2
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.3:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 5
