slot1:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.2:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 6
  TFTPProvider:
    internal: "/srv/atftp/slot1/"
    external: "slot1/"
slot2:
  location: home-lab
  USBSerialPort:
    match:
      ID_PATH: pci-0000:00:14.0-usb-0:2.3:1.0
    speed: 115200
  ModbusTCPCoil:
    host: 192.168.1.100
    coil: 5
  TFTPProvider:
    internal: "/srv/atftp/slot2/"
    external: "slot2/"
